### ISSUE TITLE
Support Bevy v0.14

### ISSUE THREAD

**Issue by umut-sahin** [jakobhellermann/bevy_editor_pls#109]
Thanks for the crate, it'd be lovely if it's supported on v0.14 :raised_hands:

**Comment by zhaop** [comment]
In the mean time you can try out #110 by adding this to your Cargo.toml (let me know if something is broken :) )

```toml
[patch.crates-io]
bevy_editor_pls = { git = "https://github.com/zhaop/bevy_editor_pls.git", branch = "bevy-0.14" }
```
